### ISSUE TITLE
hi bro i have this problem

### ISSUE THREAD

**Issue by xiazaipw** [MTDoven/AutoAiming-by-Yolov8s#3]
PS C:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main> & C:/Python39/python.exe c:/Users/Administrator/Downloads/AutoAiming-by-Yolov8s-main/Inference.py
Ultralytics YOLOv8.0.106  Python-3.9.13 torch-1.8.2+cu102 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)
YOLOv8n summary (fused): 168 layers, 3006038 parameters, 0 gradients
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 89, in <module>       
    model.predict_warm_up(img)
    return func(*args, **kwargs)
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 66, in predict_warm_up
    return self.predictor.predict_cli(source)
  File "C:\Python39\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 188, in predict_cli
    gen = self.stream_inference(source, model)
  File "C:\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 30, in stream_inference
    im = torch.permute(torch.from_numpy(source),(2,0,1))[None].to(self.model.device)/255
AttributeError: module 'torch' has no attribute 'permute'
PS C:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main> & C:/Python39/python.exe c:/Users/Administrator/Downloads/AutoAiming-by-Yolov8s-main/Inference.py
Ultralytics YOLOv8.0.106  Python-3.9.13 torch-1.8.2+cu102 CUDA:0 (NVIDIA GeForce GTX 1060 6GB, 6144MiB)
YOLOv8n summary (fused): 168 layers, 3006038 parameters, 0 gradients
Traceback (most recent call last):
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 89, in <module>
    model.predict_warm_up(img)
  File "C:\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 66, in predict_warm_up
    return self.predictor.predict_cli(source)
  File "C:\Python39\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 188, in predict_cli
    gen = self.stream_inference(source, model)
  File "C:\Python39\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "c:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main\Inference.py", line 30, in stream_inference
    im = torch.permute(torch.from_numpy((source),(2,0,1))[None].to(self.model.device)/255)
AttributeError: module 'torch' has no attribute 'permute'
PS C:\Users\Administrator\Downloads\AutoAiming-by-Yolov8s-main>

**Comment by MTDoven** [comment]
Thank you for your question.

You can focus on this line of code in
"AutoAiming-by-Yolov8s-main\Inference.py" in line 30.
    im =
torch.permute(torch.from_numpy((source),(2,0,1))[None].to(self.model.device)/255)
Here's some thing wrong with brackets, here may be the right version:
    im =
torch.permute(torch.from_numpy(source),(2,0,1))[None].to(self.model.device)/255
If it still not working, you can try:
    im = torch.from_numpy(source).permute((2,0,1))
    im = im.to(self.model.device)[None] / 255

Or you can reference to AttributeError: module 'torch' has no attribute
'permute' - PyTorch Forums
<https://discuss.pytorch.org/t/attributeerror-module-torch-has-no-attribute-permute/138448>
this
page for some information.


xiazaipw ***@***.***> 于2023年5月23日周二 18:20写道：
